### ISSUE TITLE
Make sure Templates folder gets installed during Gem install

### ISSUE THREAD

**Issue by onlydole** [dvanderbeek/leather#11]
Is there any reason why this folder does not get copied currently? I can submit a pull request if this is a desired feature!

**Comment by dvanderbeek** [comment]
Can you clarify when you are picturing this getting copied over? In the current version, it should copy all the files in the templates folder into your host app when you run rails g leather:install - is that not working properly for you?

**Comment by onlydole** [comment]
That is correct! 

I Believe the issue is due to the gemspec

``` s.files = Dir["{app,config,db,lib}/**/*", "MIT-LICENSE", "Rakefile", "README.rdoc"]```

should be 

```s.files = Dir["{app,config,db,lib,templates}/**/*", "MIT-LICENSE", "Rakefile", "README.rdoc"]```

As when I install this (have tried a few times), the only folders that get moved over are app, config, lib, and test

**Comment by dvanderbeek** [comment]
Gotcha - yeah, feel free to submit a PR if you've verified that the change fixes the issue. Thanks! Hopefully this is helpful in your app!

**Comment by dvanderbeek** [comment]
Actually, just to clarify, are you saying you've actually copied the app/config/lib/test directories into your host app? Those should not get copied when you run the install generator, only the files in templates. Everything else should just get served directly from the gem.

**Comment by onlydole** [comment]
I have submitted a pull request to alleviate that issue! I was copying the templates directory as that was not getting copied over or getting served directly from the gem (that PR fixes that problem for me though).

**Comment by onlydole** [comment]
Thank you @dvanderbeek!
